# Generated by Django 4.1.7 on 2023-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='login_failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
