# Generated by Django 4.1.7 on 2023-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_user_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failure_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
