# Generated by Django 4.1.7 on 2023-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_failedloginattempt_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
