# Generated by Django 4.1.7 on 2023-03-29 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10, verbose_name='Id')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('department', models.CharField(max_length=20, verbose_name='Department')),
                ('title', models.CharField(max_length=100, verbose_name='Position')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('description', models.TextField()),
                ('entry_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Time')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('updated_by', models.CharField(default='huziyu', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
