# Generated by Django 4.1.7 on 2023-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
